### ISSUE TITLE
`astype` in processing chain configuration files

### ISSUE THREAD

**Issue by gipert** [legend-exp/dspeed#17]
As reported by Toby, `astype` does not seem to work as expected? This, for example:
```json
{   
  "module": "numpy",
  "function": "subtract",
  "args": [
    "astype(wf_presum_float_8, 'uint16')",
    0,
    "wf_presum_8"
  ],
  "kwargs": {
    "signature": "(n),()->(n)",
    "types": "HH->H"
  },
  "prereqs": [
    "wf_presum_float_8"
  ]
}
```
Produces:
```
I don't know what to do with astype. Building output without it!
```

**Comment by gipert** [comment]
In general, I have realized we don't have unit tests for this and other special methods like `round`. We should add them! It would be good to make a list of not-currently-tested important features.

**Comment by iguinn** [comment]
This pull request will hopefully fix this issue. I also added unit tests for special methods. https://github.com/legend-exp/dspeed/pull/24
