### ISSUE TITLE
Bug: passing `dtypes` as processor arguments in DSP config files

### ISSUE THREAD

**Issue by gipert** [legend-exp/dspeed#2]
Passing `dtypes` as processor arguments in DSP config files seems broken. The following
```json
"wf_cum": {
    "function": "cumsum",
    "module": "numpy",
    "args": ["wf_blsub", 1, "'float32'", "wf_cum"],
    "kwargs": {"signature": "(n),(),()->(n)", "types": ["fiU->f"]},
    "unit": "ADC"
}
```
raises a `TypeError: Cannot construct a dtype from an array from cumsum` (same with e.g. `"'f'"`).

As a partial workaround, the following seems to work:
```json
"wf_cum": {
    "function": "cumsum",
    "module": "numpy",
    "args": ["wf_blsub", 1, 0, "wf_cum"],
    "kwargs": {"signature": "(n),(),()->(n)", "types": ["fii->f"]},
    "unit": "ADC"
}
```

**Comment by iguinn** [comment]
The reason for that is that internally, waveform is a 2-dimensional array and np.cumsum flattens 2-d arrays if you don't specify an axis. This is why we use the gufunc interface, which is good at vectorizing functions like this; unfortunately, cumsum does not implement that, so I'm not sure there is a solution to this aside from setting "axis=0".
