### ISSUE TITLE
Processors with variable numbers of outputs

### ISSUE THREAD

**Issue by iguinn** [legend-exp/dspeed#3]
For some processors we want to have a variable number of outputs. For example, a pileup processor will want to find multiple trap-maxes; @jasondet's and @SamuelBorden also want to find multiple maxes and threshold crossings for SiPM data.

The way ProcessingChain and the gufunc interface works, we want to have fixed size arrays for all inputs and outputs; we also, as a matter of principle, are trying to avoid ever allocating new memory inside of a processor. This does not prevent variable number of outputs, since we can just take the time-tested approach of allocating an array bigger than we need, filling it up to what we need, padding the remainder, and returning the array and the number of values found.

As an example, in pseudo code, a multi-max function would look like:
```py
@guvectorize(..., '(n),(m), ()', ...)
def multi_max(wf_in, max_list, n_max):
     max_list[:] = NaN or 0?
     n_max = 0
     for i in range(len(wf_in) ):
        if sample i is local maximum:
            max_list[n_max] = i
            n_max += 1
```
However, I am interested in hearing others' thoughts about this approach. Some additional thoughts about it:

1. How do we want to pad unused values? We could use NaN, but we have also discussed using that to signify errors, so this might cause problems? We could also just pad with 0.
2. If we want to propagate these results to other processors, I think vectorization might automagically apply processors once for each value (including the padded ones!). If our waveforms are size n and max_list is size m, the array broadcasting logic should broadcast a `(n), (), ()` processor into `(m, n), (m), (m)`. We are actually already taking advantage of this to process multiple waveforms at a time! However, if we choose this approach, then the processor will look at the padded values, so we need to make sure that these would have a reasonable behavior!
3. Another option for propagating results to other processors is to write specialized processors that take in the array of results and the size. For example, we might write `time_point_multi_thresh(wf_in, thresh, max_list, n_max, tp_out)`. The advantage of this approach is we could be smarter about ignoring the padded values, avoiding weird behavior and speeding the processor up. The disadvantage is that it would require a bunch of work from us to write new processors.

I'm interested in what thoughts others have. We will also want to think about how this gets added to our HDF5 files; my understanding is that variable width arrays are well supported, and in principle could work pretty similar to the above.

**Comment by gipert** [comment]
This is the function to convert `ArrayOfEqualSizedArrays` to `VectorOfVectors` that the processing chain could use:

https://legend-pydataobj.readthedocs.io/en/stable/api/lgdo.types.html#lgdo.types.arrayofequalsizedarrays.ArrayOfEqualSizedArrays.to_vov
