### ISSUE TITLE
Numba cache is not activated by default

### ISSUE THREAD

**Issue by gipert** [legend-exp/dspeed#47]
Despite #41, importing `dspeed.processors` still takes a long time (~90 seconds on my laptop) even after repeated imports, if `DSPEED_CACHE` is unset. Also confirmed by @patgo25.

**Comment by iguinn** [comment]
It works for me, both with a pip install and in the container. Here's numba's description of how the cache should work: https://numba.pydata.org/numba-doc/dev/reference/envvars.html#numba-envvars-caching.

It's first choice will be whatever is pointed to by the env variable `NUMBA_CACHE_DIR`, which I assume you aren't using?
The next choice is the In-tree cache. This is what it will do if you are running a user install of numba. This will be `[dspeed.__path__]/processors/__pycache__`
The next choice is the user-wide cache, (for me it's `$HOME/.cache/numba/processors_[hexstring]`). When I use the `legend-sw` container, this is where it ends up. This is looked up with `import appdirs; appdirs.user_cache_dir()`
The last choice is the IPython cache. For me, the ipython cache dir is `$HOME/.cache/ipython`. It's looked up using `import IPython; IPython.paths.get_ipython_cache_dir()`. I've never had it go here though.

Can you check which of these options you would expect the cache to go to, and if the cache files are going there?

**Comment by gipert** [comment]
Cannot reproduce anymore.
